from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1280, 720)
        MainWindow.setStyleSheet("background-color: rgb(219, 221, 255);")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.primary = QtWidgets.QTableWidget(self.centralwidget)
        self.primary.setGeometry(QtCore.QRect(380, 70, 521, 221))
        self.primary.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"font: 9pt \"Nirmala UI\";")
        self.primary.setObjectName("primary")
        self.primary.setColumnCount(4)
        self.primary.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.primary.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.primary.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.primary.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.primary.setHorizontalHeaderItem(3, item)
        self.secondary = QtWidgets.QTableWidget(self.centralwidget)
        self.secondary.setGeometry(QtCore.QRect(300, 340, 691, 371))
        self.secondary.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"font: 9pt \"Nirmala UI\";")
        self.secondary.setObjectName("secondary")
        self.secondary.setColumnCount(5)
        self.secondary.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.secondary.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.secondary.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.secondary.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.secondary.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.secondary.setHorizontalHeaderItem(4, item)
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(10, 10, 61, 31))
        self.label.setStyleSheet("color: rgb(0, 85, 127);\n"
"font: 14pt \"Nirmala UI\";")
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(10, 40, 91, 31))
        self.label_2.setStyleSheet("color: rgb(0, 85, 127);\n"
"font: 14pt \"Nirmala UI\";")
        self.label_2.setObjectName("label_2")
        self.rollno = QtWidgets.QLabel(self.centralwidget)
        self.rollno.setGeometry(QtCore.QRect(100, 10, 281, 31))
        self.rollno.setStyleSheet("font: 75 14pt \"MS Shell Dlg 2\";")
        self.rollno.setObjectName("rollno")
        self.name = QtWidgets.QLabel(self.centralwidget)
        self.name.setGeometry(QtCore.QRect(100, 40, 281, 31))
        self.name.setStyleSheet("font: 75 14pt \"MS Shell Dlg 2\";")
        self.name.setObjectName("name")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(470, 20, 331, 41))
        self.label_3.setStyleSheet("color: rgb(60, 25, 255);\n"
"font: 16pt \"Nirmala UI\";")
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(0, 290, 1281, 41))
        self.label_4.setStyleSheet("color: rgb(60, 25, 255);\n"
"font: 16pt \"Nirmala UI\";")
        self.label_4.setObjectName("label_4")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Attendance Report"))
        item = self.primary.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Course ID"))
        item = self.primary.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Course Name"))
        item = self.primary.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Faculty ID"))
        item = self.primary.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Attendance"))
        item = self.secondary.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Course ID"))
        item = self.secondary.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Course Name"))
        item = self.secondary.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Faculty ID"))
        item = self.secondary.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Date"))
        item = self.secondary.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "Status"))
        self.label.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:14pt; font-weight:600;\">ID</span></p></body></html>"))
        self.label_2.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:14pt; font-weight:600;\">Name</span></p></body></html>"))
        self.rollno.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:14pt;\">Roll No</span></p></body></html>"))
        self.name.setText(_translate("MainWindow", "Name"))
        self.label_3.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:14pt; font-weight:600;\">OverAll Attendence Report</span></p></body></html>"))
        self.label_4.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:14pt; font-weight:600;\">Date wise Attendence Sheet</span></p></body></html>"))

